In [1]:
import pandas as pd
import numpy as np
import pprint
import math
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv('adm_data.csv')
data = data.drop('Serial No.',axis=1)
data=(data-data.mean())/data.std()
train = data.sample(frac=0.8, random_state=200) 
validation = data.drop(train.index)
train_without_label = train.drop('Chance of Admit ',axis=1)

In [3]:
train_X = train_without_label.values  # getting the 2d matrix
train_X = np.insert(train_X,0,1,axis=1) # inserting all 1's at the first column
train_Y = train['Chance of Admit '].values
print(train_X.shape)
row = train_X.shape[0]
column = train_X.shape[1]
print(row,column)

(360, 8)
360 8


In [4]:
theta = [0 for i in range(column)]
print(theta)
learning_rate = 0.01
m = row
number_of_iteration = 500

for i in range(number_of_iteration):
    h_theta = np.matmul(train_X,theta)
    value = np.subtract(h_theta , train_Y)
    value = np.matmul(value,train_X)
    value = (learning_rate/m)*value
    theta = np.subtract(theta ,value)

theta

[0, 0, 0, 0, 0, 0, 0, 0]


array([-0.00583737,  0.18067829,  0.18093991,  0.06821172,  0.02381349,
        0.12607595,  0.3716649 ,  0.10779244])

In [5]:
validation_without_label = validation.drop('Chance of Admit ',axis=1)
validation_X = validation_without_label.values
validation_X = np.insert(validation_X,0,1,axis=1)

predicted_Y_bar = np.matmul(validation_X,theta)
predicted_Y_bar = predicted_Y_bar.tolist()
actual_Y = validation['Chance of Admit '].tolist()
print("Mean Square Error : ",r2_score(actual_Y,predicted_Y_bar))

Mean Square Error :  0.8005672893418456


In [6]:
theta1 = [0 for i in range(column)]
print(theta1)
learning_rate = 0.01
m = row
number_of_iteration = 500

for i in range(number_of_iteration):
    h_theta = np.matmul(train_X,theta1)
    numerator = np.subtract(h_theta,train_Y)
    denominator = np.absolute(np.array(h_theta) - np.array(train_Y))
    value = np.divide(numerator,denominator)
    value = np.matmul(value,train_X)
    value = (learning_rate/(2*m))*value
    theta1 = np.subtract(theta1,value)

theta1

[0, 0, 0, 0, 0, 0, 0, 0]


array([0.06816667, 0.17728737, 0.14228822, 0.08412262, 0.06138825,
       0.09143166, 0.36532333, 0.10588246])

In [7]:
validation_without_label = validation.drop('Chance of Admit ',axis=1)
validation_X = validation_without_label.values
validation_X = np.insert(validation_X,0,1,axis=1)

predicted_Y_bar = np.matmul(validation_X,theta1)
predicted_Y_bar = predicted_Y_bar.tolist()
actual_Y = validation['Chance of Admit '].tolist()
print("Mean Absolute Error : ",r2_score(actual_Y,predicted_Y_bar))

Mean Absolute Error :  0.8081854604666601


In [16]:
theta2 = [0 for i in range(column)]
print(theta2)
learning_rate = 0.05
m = row
number_of_iteration = 100

for i in range(number_of_iteration):
    h_theta = np.matmul(train_X,theta2)
    numerator = np.subtract(h_theta,train_Y)
    denominator = np.matmul(train_Y,np.absolute(np.array(h_theta) - np.array(train_Y)))  #-0.7955265183833184
    #denominator = train_Y * abs(np.array(h_theta) - np.array(train_Y))
    value = np.divide(numerator,denominator)
    value = np.matmul(value,train_X)
    value = (learning_rate/(2*m))*value
    theta2 = np.subtract(theta2,value)

theta2

[0, 0, 0, 0, 0, 0, 0, 0]


array([ 0.00058315, -0.06688467, -0.06545487, -0.05723564, -0.05659934,
       -0.05453657, -0.07193282, -0.04749411])

In [17]:
validation_without_label = validation.drop('Chance of Admit ',axis=1)
validation_X = validation_without_label.values
validation_X = np.insert(validation_X,0,1,axis=1)

predicted_Y_bar = np.matmul(validation_X,theta2)
predicted_Y_bar = predicted_Y_bar.tolist()
actual_Y = validation['Chance of Admit '].tolist()
print("Mean Absolute Percentage Error : ",r2_score(actual_Y,predicted_Y_bar))

Mean Absolute Percentage Error :  -0.793640343403796
